### ISSUE TITLE
UnicodeEncodeError of gbk

### ISSUE THREAD

**Issue by DangGwanHou** [microsoft/markitdown#79] opened 2024-12-17 02:32 UTC
```powershell
PS C:\study\其他\社会人文\毛选> markitdown .\01.pdf > 01.md
C:\software\Python310\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\software\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\software\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\software\Python310\Scripts\markitdown.exe\__main__.py", line 7, in <module>
  File "C:\software\Python310\lib\site-packages\markitdown\__main__.py", line 16, in main
    print(result.text_content)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 297: illegal multibyte sequence
```

**Comment by kentaroy47** [comment] 2024-12-17 02:59
duplicate of #78?

**Comment by wuhu1234567** [comment] 2024-12-17 04:52
Have you used conda? That package seems unofficial and appears to have some bugs. I encountered the same issue when using conda, but the problem was resolved when I switched back to pip.

**Closed** 2024-12-17 21:38 UTC
